---
# tasks file for apigee-opdk-temporary-remove-targets/
- block:
  - name: Create temporary holding folder
    file:
      path: "{{ item.temporary_holding_folder }}"
      state: directory
    with_items: "{{ temporary_move }}"

  - name: Move to temporary holding folder
    shell: "mv {{ item.original_folder }}/{{ item.file_name }} {{ item.temporary_holding_folder }}/"
    with_items: "{{ temporary_move }}"

  when: temporary_move is defined
